### ISSUE TITLE
Moved scoop to custom location. Now `sfsu` doesn't work

### ISSUE THREAD

**Issue by arnabanimesh** [winpax/sprinkles#89]
Error report: [report-5f7cd31a-32fb-45bd-abab-b2d2b740d035.toml.txt](https://github.com/user-attachments/files/16931241/report-5f7cd31a-32fb-45bd-abab-b2d2b740d035.toml.txt)

Followed these steps to move `scoop`: https://github.com/ScoopInstaller/Scoop/issues/3852#issuecomment-1417160249

**Comment by jewlexx** [comment]
Can you provide the following:
1. Your Scoop config (without any sensitive values (i.e your VirusTotal API Key)
2. The output of `$env:SCOOP`
3. Your actual Scoop path

Sprinkles checks the Scoop config, followed by the `SCOOP` environment variable, and then finally defaults to `$HOME/scoop`. If the first two options aren't set and Scoop isn't at the default location, then it won't be able to find your Scoop install.

**Comment by arnabanimesh** [comment]
`SCOOP` env var was not set. Now it is working. Closing the issue.
